version: '3.8'

services:
  app:
    image: ${DOCKERHUB_USERNAME}/construct-backend:${SHORT_SHA}
    container_name: fastapi-app
    restart: always
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_ACCESS_EXPIRE=${JWT_ACCESS_EXPIRE}
      - REFRESH_EXPIRE=${REFRESH_EXPIRE}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
