"""company_update

Revision ID: 9899928caee4
Revises: 5bc68203d6cf
Create Date: 2025-07-21 18:32:04.281929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9899928caee4'
down_revision: Union[str, Sequence[str], None] = '5bc68203d6cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'companies', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'user_id')
    # ### end Alembic commands ###
