"""Initial migration

Revision ID: a15e872d3bdd
Revises: 
Create Date: 2025-07-01 00:55:14.317139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a15e872d3bdd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'chat_messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'chat_messages', 'users', ['recipient_id'], ['id'])
    op.alter_column('order_views', 'status',
               existing_type=sa.VARCHAR(length=24),
               type_=sa.SmallInteger(),
               existing_nullable=True)
    op.create_foreign_key(None, 'order_views', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'image_url',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=511),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'image_url',
               existing_type=sa.String(length=511),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'order_views', type_='foreignkey')
    op.alter_column('order_views', 'status',
               existing_type=sa.SmallInteger(),
               type_=sa.VARCHAR(length=24),
               existing_nullable=True)
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    # ### end Alembic commands ###
