"""company_update

Revision ID: a5bfa6b05b31
Revises: 9899928caee4
Create Date: 2025-07-21 18:55:10.165684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5bfa6b05b31'
down_revision: Union[str, Sequence[str], None] = '9899928caee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('inn', sa.String(length=10), nullable=False))
    op.drop_constraint(op.f('companies_name_key'), 'companies', type_='unique')
    op.create_index(op.f('ix_companies_inn'), 'companies', ['inn'], unique=True)
    op.drop_constraint(op.f('companies_user_id_fkey'), 'companies', type_='foreignkey')
    op.drop_column('companies', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('companies_user_id_fkey'), 'companies', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_companies_inn'), table_name='companies')
    op.create_unique_constraint(op.f('companies_name_key'), 'companies', ['name'])
    op.drop_column('companies', 'inn')
    # ### end Alembic commands ###
