"""initial

Revision ID: b2df2281d618
Revises: 
Create Date: 2025-07-04 17:28:02.554546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2df2281d618'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('chat_messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_foreign_key(None, 'chat_messages', 'users', ['recipient_id'], ['id'])
    op.create_foreign_key(None, 'chat_messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'order_views', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.add_column('reviews', sa.Column('content', sa.Text(), nullable=False))
    op.add_column('reviews', sa.Column('sender_id', sa.UUID(), nullable=True))
    op.add_column('reviews', sa.Column('recipient_id', sa.UUID(), nullable=True))
    op.alter_column('reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_constraint(op.f('reviews_order_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'users', ['recipient_id'], ['id'])
    op.create_foreign_key(None, 'reviews', 'users', ['sender_id'], ['id'])
    op.drop_column('reviews', 'order_id')
    op.drop_column('reviews', 'user_id')
    op.drop_column('reviews', 'text')
    op.alter_column('users', 'image_url',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=511),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'image_url',
               existing_type=sa.String(length=511),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    op.add_column('reviews', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('reviews', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('reviews', sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_order_id_fkey'), 'reviews', 'orders', ['order_id'], ['id'])
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.alter_column('reviews', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('reviews', 'recipient_id')
    op.drop_column('reviews', 'sender_id')
    op.drop_column('reviews', 'content')
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'order_views', type_='foreignkey')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.alter_column('chat_messages', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('chat_messages', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
