"""initial

Revision ID: be437c53b21c
Revises: 475e995da281
Create Date: 2025-07-04 19:20:46.309229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be437c53b21c'
down_revision: Union[str, Sequence[str], None] = '475e995da281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chat_messages_recipient_id_fkey'), 'chat_messages', type_='foreignkey')
    op.drop_constraint(op.f('chat_messages_sender_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_messages', 'users', ['recipient_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('order_views_user_id_fkey'), 'order_views', type_='foreignkey')
    op.drop_constraint(op.f('order_views_order_id_fkey'), 'order_views', type_='foreignkey')
    op.create_foreign_key(None, 'order_views', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'order_views', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('orders_user_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('reviews_sender_id_fkey'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('reviews_recipient_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'users', ['recipient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_recipient_id_fkey'), 'reviews', 'users', ['recipient_id'], ['id'])
    op.create_foreign_key(op.f('reviews_sender_id_fkey'), 'reviews', 'users', ['sender_id'], ['id'])
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_user_id_fkey'), 'orders', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'order_views', type_='foreignkey')
    op.drop_constraint(None, 'order_views', type_='foreignkey')
    op.create_foreign_key(op.f('order_views_order_id_fkey'), 'order_views', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(op.f('order_views_user_id_fkey'), 'order_views', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_sender_id_fkey'), 'chat_messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(op.f('chat_messages_recipient_id_fkey'), 'chat_messages', 'users', ['recipient_id'], ['id'])
    # ### end Alembic commands ###
