"""initial

Revision ID: cbdc4100b669
Revises: 0a9f643d1fab
Create Date: 2025-07-04 19:29:54.522894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbdc4100b669'
down_revision: Union[str, Sequence[str], None] = '0a9f643d1fab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_views', 'status',
               existing_type=sa.VARCHAR(length=24),
               type_=sa.SmallInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_views', 'status',
               existing_type=sa.SmallInteger(),
               type_=sa.VARCHAR(length=24),
               existing_nullable=True)
    # ### end Alembic commands ###
